### ISSUE TITLE
unable to paste text that I copy/cut to the clipboard from the "Save As..." dialog box

### ISSUE THREAD

**Issue by oniwo** [pulsar-edit/pulsar#1127]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

I am working on a project with so many files. some of the files internally reference files on the filesystem using their filesystem name. Mostly, I am not sure which file is accessing a certain file. Instead of typing the name of the referenced file to locate where it is referenced, I open the file, then activate the "File, Save As..." dialog box, copy  or cut the file's filename and cancel the dialog box. Then activate "Find, Find in Project" and encounter the problem - I cant paste the text into the text to search text box. 

### Pulsar version

1.110.2023110716

### Which OS does this happen on?

🐧 Red Hat based (Fedora, Alma, RockyLinux, CentOS Stream, etc.)

### OS details

Fedora 41

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

1. Create a new File or Open an Existing File
2. Activate "File, Save As..." dialog box
3. Copy/Cut the filename (If there is no filename type some text and then Copy/Cut it)
4. Cancel the dialog box (click Cancel or tap Esc key) to go back to file editing
5. Paste the text on the clipboard. (the editor freezes)

### Additional Information:

I go around the problem by first pasting the text in another application, then cut/copy it to the clipboard from that application, then come back to pulsar and now paste without any problem.
![Screenshot from 2024-10-31 08-01-05](https://github.com/user-attachments/assets/866c482c-365f-4ce9-9b23-baf15e0803d6)
![Screenshot from 2024-10-31 08-40-01](https://github.com/user-attachments/assets/ff65ad42-0c5d-47b4-9d8d-2669fbfc20ab)

**Comment by savetheclocktower** [comment]
I don't know exactly what's going on with that yet, but the good news is that I can probably streamline your workflow.

Open [your init file](https://docs.pulsar-edit.dev/customizing-pulsar/the-init-file/) and paste this in:

```js
const Path = require('path');

atom.commands.add('atom-text-editor', {
  'custom:copy-active-editor-file-name-to-clipboard': () => {
    let editor = atom.workspace.getActiveTextEditor();
    let filePath = editor.getPath();
    if (!filePath) return;
    atom.clipboard.write(Path.basename(filePath));
  }
});
```

Then save and run the command **Editor: Reload Window**.

Now, whenever you're in an editor, you can open the [command palette](https://docs.pulsar-edit.dev/using-pulsar/basics/#command-palette) and run **Custom: Copy Active Editor File Name To Clipboard** to put the file’s name in your clipboard automatically.

---

On another note: we're up to Pulsar 1.122, so you might find it useful to update. (I doubt it would fix this bug, but we've fixed a lot of other bugs since then!)

**Comment by oniwo** [comment]
thank you so much. I have updated to 1.122.0 and indeed the bug is still there.

**Comment by asiloisad** [comment]
I can't reproduce it mm / win10x64 pulsar 1.122
