### ISSUE TITLE
MEGA-ISSUE: Syntax highlighting in `language-python`

### ISSUE THREAD

**Issue by savetheclocktower** [pulsar-edit/pulsar#880]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

This will serve as a catch-all issue for any problems you may encounter with syntax highlighting in REPLACE files (`language-python`). If you have problems with the new syntax highlighting (or folds, or indents) that are specific to `.py` files, keep reading.

### Something isn't highlighting correctly!

If you’ve found any highlighting regressions since 1.113:

First, please **scroll down and see if someone else has reported the issue**. If so, then you need only sit back and wait for a fix — most issues will be fixed in version 1.114!

If not, please comment with

* A small amount of sample code to reproduce the issue
* Screenshots (before and after would be ideal, but just the “after” is OK for obvious things

### I want to go back to the old highlighting!

You can easily opt out of the new Tree-sitter highlighting for any language, but first please:

* **subscribe to this issue** so you'll know when the problem is fixed
* **remove the config change** when the next release comes out so that you can enjoy the new grammar once again

To revert to the old Tree-sitter grammar for this language only, add the following to your `config.cson`:

```coffeescript
".python.source":
  core:
    useLegacyTreeSitter: true
```

To revert to the TextMate-style grammar for this language only, add the following to your `config.cson`:

```coffeescript
".python.source":
  core:
    useTreeSitterParsers: false
```

### Pulsar version

1.113

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

x

### Which CPU architecture are you running this on?

None

### What steps are needed to reproduce this?

x

**Comment by matbme** [comment]
Python parser also seems to be out-of-date. The `.wasm` in language-python package is from 10 months ago, and the tree-sitter-python repo has seen a couple of updates since then.

The `not in` inside an if statement also doesn't get properly highlighted.
Example:
```python
if tag not in self.all_steps:
    self.all_steps[tag] = 0
```
Inspector:
```
if_statement
  condition: comparison_operator
    identifier
    attribute
      object: identifier
      attribute: identifier
```

**Comment by savetheclocktower** [comment]
Awesome, thanks. I'll update to the latest `tree-sitter-python` today and get these fixes in.

**Comment by matbme** [comment]
`break` statement also isn't highlighted. Probably missing definition in `highlighs.scm`, should be alongside `continue`, which is marked as `@keyword.control.repeat._TYPE_.python`

**Comment by savetheclocktower** [comment]
OK, updated to latest `tree-sitter-python` and applied those fixes. [Here's the commit](https://github.com/pulsar-edit/pulsar/pull/859/commits/dcf451cf1b21b2fd2c34c01e8f579dc134b34567). Thanks! Let me know if you find anything else.

**Comment by asiloisad** [comment]
![image](https://github.com/pulsar-edit/pulsar/assets/29706474/fdd1be99-6257-4cd1-883a-a8d512cca553)

`break` has not assigned scope

**Comment by asiloisad** [comment]
The modern tree-sitter auto-indent is broken if multiple cursor is used. Tested in safe mode.

1. a state before
![image](https://github.com/pulsar-edit/pulsar/assets/29706474/5dc775a7-0202-4cb7-b121-6be70051c06c)
2. press Enter
3. state after
a) legacy tree-sitter
![image](https://github.com/pulsar-edit/pulsar/assets/29706474/f6fa0080-cb61-46f2-b625-b479242d9b76)
b) modern tree-sitter
![image](https://github.com/pulsar-edit/pulsar/assets/29706474/bdd7b2e0-e175-4ca2-ad6b-b67991ee37b3)

**Comment by savetheclocktower** [comment]
@Askaholic thanks so much for the detailed feedback! Item 1 is an intentional design decision (which I can elaborate on when I get a chance), and item 2 is unintentional (and therefore a bug).

I'd encourage you to give it a week or so to see if you get used to the variable highlighting differences… but if you still hate them then, we can tell you how to use your user stylesheet to get the old highlighting behavior back. Meanwhile, I'll investigate the issue with folds.

Thanks for the report!

**Comment by asiloisad** [comment]
pulsar v1.115.0: modern tree-sitter do not assign a css class to injected language-todo. In previous version it works correctly (v1.114.0, but not sure).

modern tree-sitter (and legacy tree-sitter)
![image](https://github.com/pulsar-edit/pulsar/assets/29706474/73a943d7-3361-4bf8-8c13-94c378b479d2)

textmate grammar
![image](https://github.com/pulsar-edit/pulsar/assets/29706474/32d39858-4942-488d-b392-0b931f1d32b8)

**Comment by Askaholic** [comment]
Here's another issue I noticed with the indentation hinting. It doesn't seem to get class attributes with annotations correct:

Before:
![image](https://github.com/pulsar-edit/pulsar/assets/17941539/36221eae-9a7c-4b11-8495-4e8d8c263722)

After:
![image](https://github.com/pulsar-edit/pulsar/assets/17941539/0ef89b7e-cb5b-4b1a-8d4d-6f097814274b)

I would expect the cursor to be one level of indentation back from where it is.

Here are other examples that I've tried which have the same result:

```python
class Foo:
    field1: int = 10
```

```python
class Foo:
    field1: int = 10,
```

```python
class Foo:
    field1: list[int]
```

However, these work correctly:
```python
class Foo:
    field1
```

```python
class Foo:
    field1,
```

```python
class Foo:
    field1 = 10
```

**Comment by savetheclocktower** [comment]
That was dumb of me for assuming that every occurrence of a colon was a hint that the next line should be indented — which I think _would_ be true if not for type annotations. I can update it to enforce that the colon has to occur at the end of the line.

**Comment by savetheclocktower** [comment]
> That was dumb of me for assuming that every occurrence of a colon was a hint that the next line should be indented — which I think _would_ be true if not for type annotations. I can update it to enforce that the colon has to occur at the end of the line.

Almost forgot about this one, but [got it](https://github.com/pulsar-edit/pulsar/pull/968/commits/03af1244d327ce8942d8e171466891e92a13eff7) into #968. Thanks for the report, @Askaholic!

**Comment by asiloisad** [comment]
If first two character are upper cased, then element has `support.other.function.python` class instead of `support.type.constructor.python`.
![image](https://github.com/pulsar-edit/pulsar/assets/29706474/b2bc30a7-1a6f-454a-9662-1089c3e34901)

**Comment by savetheclocktower** [comment]
> If first two characters are upper cased, then element has `support.other.function.python` class instead of `support.type.constructor.python`. ![image](https://private-user-images.githubusercontent.com/29706474/321834010-b2bc30a7-1a6f-454a-9662-1089c3e34901.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4OTMyNjUsIm5iZiI6MTcxMjg5Mjk2NSwicGF0aCI6Ii8yOTcwNjQ3NC8zMjE4MzQwMTAtYjJiYzMwYTctMWE2Zi00NTRhLTk2NjItMTA4OWMzZTM0OTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDAzMzYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMjM4NTQ2NmExZWY0MDEzZTdjNzE3MTU0OGJkNThhMmM2YTU4MzE0MjEwYmVmNWZhZTk0MTBlMmYxMGVlYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fofpsCENoZcEmU3qgemZFMdrmm05RVm1Lsagw68Bozw)

Easy fix; added to #968. Thanks!

**Comment by savetheclocktower** [comment]
> Hey, I've been using pulsar for the last few months and its been working great for me! However, I noticed that the visual issue with folds that I described [here](https://github.com/pulsar-edit/pulsar/issues/880#issuecomment-1997837479) is still happening on pulsar 1.118.
> 
> Thanks for continuing to work on this project!

I should've at least given you the workaround for your first issue (variable assignments not sharing a color with variable usage). You can add this to your user stylesheet:

```less
@import "syntax-variables"; // (this line may already be present)

.syntax--source.syntax--python .syntax--variable {
  color: @syntax-text-color;
}
```

As for the other issue: it slipped through the cracks, I'm afraid. I'll take a look today and make sure that a fix gets made for 1.119. Thanks for the reminder!

**Comment by savetheclocktower** [comment]
> 2\. **Code folds on brackets don't show the closing bracket.** In atom if you fold on a dictionary or list as shown below, it will render as `{...}` or `[...]`, however it seems with modern treesitter the closing bracket is dropped `{...` or `[...`.

This is finally fixed in [this commit](https://github.com/pulsar-edit/pulsar/pull/1028/commits/d7faa84e5ae413d10d7c0a0cf9a9dc019c7f3b11). #1028 should land just before the 1.119 release in mid-July. Thanks for your patience!

**Comment by asiloisad** [comment]
There is a problem with links if string is more than link.

![image](https://github.com/user-attachments/assets/f19736a5-b1df-41ff-bfe6-12ead32b4e38)

**Comment by savetheclocktower** [comment]
> There is a problem with links if string is more than link. Pulsar v1.122.0

Seems like a problem with my `tree-sitter-hyperlink` parser. I'll take a look. Thanks!

**Comment by savetheclocktower** [comment]
@asiloisad, this is fixed in #1118 and will go out next month. Thanks!

**Comment by mzivic7** [comment]
> That was dumb of me for assuming that every occurrence of a colon was a hint that the next line should be indented — which I think _would_ be true if not for type annotations. I can update it to enforce that the colon has to occur at the end of the line.

There are more cases like this:
```py
# wrongly indenting next line:
my_list[3:6]   # list slicing
my_list[::-1]   # list slicing (syntax: string[start:end:step])
if True: print("ok")   # oneliners
for x in my_list: print(x)   # also oneliner, same with while

# these are NOT wrongly indenting:
x = lambda a : print(a)   # lambda functions
my_dict = {"a": 1, "b": 2}   # dicts
```
So only when colon is at the end of the string, excluding comments, next line should be indented.

**Comment by savetheclocktower** [comment]
> There are more cases like this:

#1172 should fix these. Thanks for the report!

**Comment by asiloisad** [comment]
https://github.com/pulsar-edit/pulsar/issues/1216

**Comment by asiloisad** [comment]
If lambda is used as a key positioned argument, then `=` is marked incorrectly (as lambda too).

![Image](https://github.com/user-attachments/assets/413e2e47-2239-4b9e-b89c-e14b421ab0b0)

**Comment by savetheclocktower** [comment]
> If lambda is used as a key positioned argument, then `=` is marked incorrectly (as lambda too).
> 
> ![Image](https://github.com/user-attachments/assets/413e2e47-2239-4b9e-b89c-e14b421ab0b0)

In your theme, are operators and keywords the same color?

If `=` is the same color in both your example above and

```python
max(key=x)
```

then it may be as simple as that.

Upon examination, `=` is scoped as `keyword.operator` and `lambda` is scoped as `keyword.control`. It's not typical for an operator and a keyword to be right next to one another, so that might be enough to make it feel weird by itself.

This also might imply that `lambda` is better to think of as an annotation like `def` instead of a control-flow keyword like `if` or `for`— hence should have a scope like `storage.type.function.lambda.python`. That'd produce a result like this in my theme:

<img width="183" alt="Image" src="https://github.com/user-attachments/assets/a5a1884c-ad1d-4237-8dcd-e1941c402b5e" />

**Comment by asiloisad** [comment]
nvm, I have made two mistakes: 
- Wrong cursor position while log cursor scope is used, 
- I have never notice, that `=` has a color another than black.
It's not the editor who makes the mistakes, it's the debugger 😅

**Comment by aliqandil** [comment]
I don't think this one is a regression, but a new feature that's not yet supported, I'll put it here regardless:

How an except* clause looks: (v1.129.0)
<img width="982" height="159" alt="Image" src="https://github.com/user-attachments/assets/0ec72fc9-b4e2-4a10-8380-9ac38f805f26" />

How it should look: [From Python Docs](https://docs.python.org/3/library/exceptions.html#lib-exception-groups)
<img width="988" height="662" alt="Image" src="https://github.com/user-attachments/assets/6c1bb50d-4578-4053-8e39-661fcb9c37f7" />

**Comment by savetheclocktower** [comment]
> I don't think this one is a regression, but a new feature that's not yet supported, I'll put it here regardless:

The existing `tree-sitter-python` parser version we're using supports it, so it was just a matter of adding the syntax highlighting. I've addressed this in #1320 and it'll go out in the next release. Thanks!

**Comment by TristynAlxander** [comment]
I opened an [issue](https://github.com/pulsar-edit/pulsar/issues/1360) that may be better placed under this mega thread.

In short, for the python collapsing function comments at the start of `if` blocks prematurely end the block. Possibly also relevant, in an older version comments at the end of the block were excluded. That's not an issue in the current version, but it may be related. Interestingly, this isn't an issue in `while` blocks. 

Example:
```
# This Collapses is Broken
if(True):
  # Only this comment Disappears
  pass # This remains
  # Comment - this remains
```

**Comment by savetheclocktower** [comment]
Yeah, this is a limitation of the folding system that won't be fixed properly until it gets a proper overhaul. (Explanation below is only useful for posterity and for anyone who has familiarity with Tree-sitter.)

We can fold an arbitrary range of the Tree-sitter tree. If it's not as simple as “fold this entire node,” we can adjust the boundaries of the fold match… but only going off of node positions. I can't say “move the end of the fold to the end of the `block` node; I have to say “move the end of the fold to the end of the second named child.” Whenever assumptions are violated (like when a `comment` node gets in the way of our counting), the folding doesn't work right.

To fix this, one of two things would need to happen:

1. I'd need to expand the syntax used to refer to nodes so that it can consider node names.
2. I'd need to move to a more sophisticated custom predicate logic that allows me to define several different captures within a query and use those captures to set the boundaries.

Option 1 would be less effort, but Option 2 needs to happen for a lot of other reasons, so I'll try to hold out for that one.

ETA is probably a few months; I'm purposefully refusing to work on that until we get the Electron upgrade out the door.

**Comment by TristynAlxander** [comment]
Additional Unrelated Bug, related strictly to highlighting. `PDB` seems to be highlighted as a key word, but it isn't a keyword. I mean, I'm glad Protein Data Bank is getting more attention, but I am slightly confused as to why. Google says Python DeBugger, but that's a module and still not a key word. Not a major issue, but it shouldn't be highlighted.

**Comment by savetheclocktower** [comment]
> Additional Unrelated Bug, related strictly to highlighting. `PDB` seems to be highlighted as a key word, but it isn't a keyword. I mean, I'm glad Protein Data Bank is getting more attention, but I am slightly confused as to why. Google says Python DeBugger, but that's a module and still not a key word. Not a major issue, but it shouldn't be highlighted.

Do you have an example in context? For me, `PDB` is highlighted like a constant, since it's in all-caps.

**Comment by TristynAlxander** [comment]
Oh, that makes sense. Nevermind, my bad. I assumed it was key word because the highlighting was the same as `True`, but constant makes sense too. Just didn't expect it to do that I guess. Not something I'd normally bother to report since this exact 'oops I'm dumb' situation can arise, but I was already here and I guess the AI that popped up with google gave me undue confidence it was being highlighted as part of some python de-bug module, but I was actually just confused.

*Edit:* Actually, I'm not sure all caps can really be said to be a constant. While that is convention, it's also convention to use camel case for class names, so if your class name is an acronym (e.g. ProteinDataBank -> PDB) there's some ambiguity. You could say I should name my class ProteinDataBank or PDBFile or PdbFile or PDBProcessor or PDBParser, but I'm not sure telling people to use longer less concise class names is like telling them to make narrower classes and has ever been particularly convincing or effective...

**Comment by savetheclocktower** [comment]
> Yeah, this is a limitation of the folding system that won't be fixed properly until it gets a proper overhaul. (Explanation below is only useful for posterity and for anyone who has familiarity with Tree-sitter.)

I actually figured out a simpler fix for this and it'll ship as part of #1377. At any rate, since this issue is also documented at #1360, I think we can safely close out this mega-issue and go back to individual tickets for Python grammar issues. Hence I'm closing this issue!
